nyc_realestate_spider/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('spider1/',include('spider1.urls')),
]

spider1/urls.py
from django.urls import path, include
from . import views
app_name = "spider1"
urlpatterns = [
path('', views.home, name='home'),
path('home', views.home,name = "home"),
path("create_db_notice/", views.create_db_notice, name="create_db_notice"),
path("inv_rec/", views.inv_rec, name="inv_rec"),
path("inv_rec_detail/<int:pk>", views.inv_rec_detail, name="inv_rec_detail"),
path("undone_recs_detail/<int:ll>/", views.undone_recs_detail, name = "undone_recs_detail"),
path ("inv_rec_update/", views.inv_rec_update, name = "inv_rec_update"),
path ("write_notices_to_file/", views.write_notices_to_file, name = "write_notices_to_file"),
path ("handle_undone_notices/<int:ref_id>", views.handle_undone_notices, name = "handle_undone_notices"),


]

spider1/models.py
from typing import ChainMap
from django.db import models
from django.db.models.fields import CharField, DateField, DateTimeField, TextField
from django.db.models.fields.related import ForeignKey
from django.utils import timezone
# from datetime import datetime
# from dateutil import tz
# Create your models here.
class ScrapeRecordsInventory(models.Model):
    rec_date = CharField( max_length=30)
    time_rec =  DateTimeField(default= timezone.now, blank=True )#CharField(max_length=150, default = "None")


    def __str__(self):
        return self.id 
 
class ScrapeRecords(models.Model):
    owners_name =CharField(max_length= 100)
    property_value_current_year =  CharField(max_length=100)
    property_value_next_year = CharField(max_length=100)
    tax_value = CharField(max_length=100)
    billing_address =  CharField( max_length= 500, default="None")
    link = CharField(max_length= 300, default="None")
    borough = CharField(max_length = 100, default="None")
    block = CharField(max_length=100, default="None")
    lot = CharField(max_length= 100, default="None")
    record_ref = ForeignKey(ScrapeRecordsInventory, on_delete=models.CASCADE)

    def __str__(self):
        return self.owners_name
class UndoneNotices(models.Model):
    borough = CharField(max_length= 100, default="None")
    block = CharField(max_length= 100, default = "None")
    lot = CharField(max_length=100, default = "None" )
    exception_type = CharField(max_length=200, default="None")
    billing_address =  CharField( max_length= 500, default="None")
    # time_exception =  DateTimeField(default= datetime.now(tz=tz.gettz()), blank=True )#CharField(max_length=150, default = "None")
    time_exception =  DateTimeField(default= timezone.now, blank=True)#CharField(max_length=150, default = "None")

    scrape_rec = ForeignKey(ScrapeRecordsInventory, on_delete = models.CASCADE )
    exception_info = TextField(default = "NULL")

    def __str__(self):
        return str(self.exception_type)

spider1/forms.py
# from crispy_forms.helper import FormHelper
# from crispy_forms.layout import Submit
from django import forms
from .models import *
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.contrib.auth import password_validation
#from autho.models import Users
from django.contrib.auth.hashers import make_password
# Create your forms here.
#validators
def validate_my_email(email):
    try:
        validate_email(email)
        return email
    except forms.ValidationError:
        print("Email errors")
        raise forms.ValidationError(("Your email is invalid"))

class RegistrationForm(forms.Form):
    first_name=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}), label="First Name")
    surname =forms.CharField(widget=forms.TextInput(attrs={'class':'form-control input-sm'}), label='Surname')
    last_name=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}), label="Last Name")
    dob=forms.CharField(widget=forms.TextInput(attrs={'class': 'datepicker form-control input-sm' ,'data-type': 'dateIso'}), label="DOB")
    phone =forms.CharField(widget=forms.TextInput(attrs={'class':'form-control input-sm'}), label='Phone')
    email=forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}), label="Email", validators = [validate_my_email])
    national_id=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}), label="National Id / Passport")
    date_time_of_registration =forms.CharField(widget=forms.TextInput(attrs={'class':'form-control input-sm'}), label='Date of Reg')
    gender=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm' }), label="Gender")
    marital_status=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}), label="Marital Status")
    patient_no =forms.CharField(widget=forms.TextInput(attrs={'class':'form-control input-sm'}), label='Patient No')
    city=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}), label="City")
    village = forms.CharField(widget = forms.TextInput(attrs={'class':'form-control input-sm'}), label="Village")
#forms
class TestForm1(forms.Form):
    name=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label="Name",validators=[validate_my_email])
    age =forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}), label='Age')
    text=forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}), label="Text")
# class TestForm2(forms.Form):
#     name=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label="Name")
#     age =forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}), label='Age')
#     text=forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}), label="Text")
#     def __init__(self, *args, **kwargs):
#        super(TestForm2, self).__init__(*args, **kwargs)
#        self.helper = FormHelper()
#        self.helper.form_id = 'id-test-form'
#        self.helper.form_method = 'post'
#        self.helper.form_action = 'add_crispy_test'
#        self.helper.add_input(Submit('submit', 'save'))

# class ModelTestForm1(forms.ModelForm):
#     class Meta:
#         model = Test
#         fields = ('name','age', 'text',)

spider1/views.py
from django.http.response import JsonResponse
import tabula
import pandas as pd
import urllib.request
import PyPDF2
import io
import sys
import  numpy as np

from pathlib import Path
from datetime import datetime
from dateutil import tz
from selenium import webdriver
from selenium.webdriver.firefox import firefox_profile
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

from django.shortcuts import render
# Create your views here.
from .models import ScrapeRecordsInventory,ScrapeRecords,UndoneNotices
BASE_DIR = Path(__file__).resolve().parent.parent

def clean_time(raw_date, raw_time):
    aquired_time = datetime.strptime(raw_date+" "+raw_time+":00", '%Y-%m-%d %H:%M:%S')
    aquired_time_tz = datetime.astimezone(aquired_time,tz=tz.gettz())
    print("aquired time: "+ str(aquired_time_tz))
    return aquired_time_tz

def get_tax_value(tax_value_link):
    req = urllib.request.Request(tax_value_link, headers={'User-Agent' : "Magic Browser"})
    remote_file = urllib.request.urlopen(req).read()
    remote_file_bytes = io.BytesIO(remote_file)
    pdfdoc_remote = PyPDF2.PdfFileReader(remote_file_bytes)
    req_str = ""
    for i in range(pdfdoc_remote.numPages):
        current_page = pdfdoc_remote.getPage(i)
        
        str_in_qtn = current_page.extractText()
        if i == 0:
            offset = str_in_qtn.find('Amount Due')+11
            offset2 = str_in_qtn.find('Please pay')
            print(str_in_qtn.find('Amount Due'))
            print("========================================For the TAX=================================")
            req_str = str_in_qtn[offset:offset2]
            print(req_str)    
            

    # print("=========================================Tax Value Link============================================")
    # print(tax_value_link)
    return req_str

def get_property_value(property_value_link):
    property_value_dict = {}
    dfs3 = tabula.read_pdf(property_value_link,  pages='3')
    print("Property Value")
    print("==============Property Value Current Year: "+ str(dfs3[0]["Current Year (2020-21)"][0]))
    print("==============Property Next Year: "+ str(dfs3[0]["Next Year (2021-22)"][0]))
    print("========================================Property Value Link========================================")
    print(property_value_link)
    property_value_dict["Current Year (2020-21)"] = dfs3[0]["Current Year (2020-21)"][0]
    property_value_dict["Next Year (2021-22)"] = dfs3[0]["Next Year (2021-22)"][0]

    return property_value_dict
def my_timer(limit):
    
    wait_time = np.random.randint(1,limit) 
    print("Limit time is: "+str(limit)+", Wait time is: "+str(wait_time))
    return wait_time


def nyc_spider(notice_recs, record_id):
    req_values_list = []
    profile = webdriver.FirefoxProfile()

    profile.set_preference("network.proxy.type", 1)
    profile.set_preference("network.proxy.socks", "127.0.0.1")
    profile.set_preference("network.proxy.socks_port", 9150)
    profile.set_preference("network.proxy.socks_version", 5)
    profile.update_preferences()
    # my_url ="https://a836-pts-access.nyc.gov/care/Search/Disclaimer.aspx?FromUrl=../search/commonsearch.aspx?mode=address"
    # service = Service(browser_path)                                            
    my_url ="https://a836-pts-access.nyc.gov/care/Search/Disclaimer.aspx?FromUrl=../search/commonsearch.aspx?mode=persprop"

    options = Options()
    # options.set_preference('profile', profile)

    # driver = webdriver.Firefox(firefox_profile=profile, options=options)

    scrapeRecordsInventoryRef =  ScrapeRecordsInventory.objects.get(id = record_id)
    with webdriver.Firefox(firefox_profile = profile, options= options) as driver:
        driver.get(my_url)
        # Setup wait for later
        wait = WebDriverWait(driver, 70)
        wait.until(EC.element_to_be_clickable((By.ID, 'btAgree')))
        driver.find_element(By.ID, "btAgree").click() 
        
        count = 0
        for index, rec in notice_recs.iterrows():
            print("++++==============================================================")
            try:
                count = count+1
                print("--------------------------------------------------------------------------------------------------")
                print("Rec total number = "+ str(len(notice_recs))+" remaining records = "+ str(len(notice_recs)-count))
                print("Count = "+str(count))
                print("--------------------------------------------------------------------------------------------------")
                wait2 = WebDriverWait(driver, 100)
                wait2.until(EC.element_to_be_clickable((By.XPATH,"//div[@id ='secondarytopmenu']/ul/li[2]/a")))
                driver.find_element(By.XPATH, "//div[@id ='secondarytopmenu']/ul/li[2]/a").click()
            # Store the ID of the original window
            # original_window = driver.current_window_handle

            # Check we don't have other windows open already
            # assert len(driver.window_handles) == 1

            # Click the link which opens in a new window
            # wait.until(EC.element_to_be_clickable((By.CLASS_NAME, 'selenium-webdriver')))
            # driver.find_element(By.CLASS_NAME, "selenium-webdriver").click()
            
            
                wait.until(EC.element_to_be_clickable((By.ID, 'btSearch')))
                # driver.find_element(By.ID,"inpStreet").send_keys("All")
                borough_dropdown = Select(driver.find_element(By.ID,"inpParid"))
                borough_dropdown.select_by_index(rec["borough"])
                driver.find_element(By.ID,"inpTag").send_keys(str(rec["block"]))
                driver.find_element(By.ID, "inpStat").send_keys(str(rec["lot"]))
                driver.find_element(By.ID, "btSearch").click()
                wait.until(EC.element_to_be_clickable((By.XPATH, "//ul[@class='navigation']/li[1]")))
                owner_name = driver.find_element(By.XPATH, "//table[@id='Property Owner(s)']/tbody/tr[2]/td").text
                # owner_name = driver.find_element(By.XPATH, "//table[@id='Property sdsdOwner(s)']/tbody/tr[2]/td").text

                wait.until(EC.element_to_be_clickable((By.XPATH, "//ul[@class='navigation']/li[6]")))

            # //table[@id="Property Owner(s)"]/tbody/tr[2]/td
            
                driver.find_element(By.XPATH, "//ul[@class='navigation']/li[6]").click()
                wait.until(EC.element_to_be_clickable((By.XPATH,"//table[@id='Notices of Property Value']/tbody/tr[2]/td[2]/a[@href]")))
                property_value_link = driver.find_element(By.XPATH,"//table[@id='Notices of Property Value']/tbody/tr[2]/td[2]/a").get_attribute('href')

                # //table[@id='Notices of Property Value']/tbody/tr[2]/td[2]/a[@href]
                driver.find_element(By.XPATH, "//ul[@class='navigation']/li[7]").click()
                tax_value_link = driver.find_element(By.XPATH, "//table[@id='Property Tax Bills']/tbody/tr[2]/td[3]/a").get_attribute('href')
                print("Propert Value Link")
                print(property_value_link)
                print("Tax Value Link")
                print(tax_value_link)
                print("Owner Name")
                print(owner_name)    
                tax_value = get_tax_value(tax_value_link)
                property_value = get_property_value(property_value_link)
                print("propert value")
                print(property_value)
                print("Tax Value")
                print(tax_value)
                req_values_list.append(owner_name)
                req_values_list.append(tax_value)
                req_values_list.append(property_value)
                ## First Table
                # scrapeRecordsInventoryRef =  ScrapeRecordsInventory.objects.get(id = record_id)
                ##Get rec from first table and use it to reference this

                if "street_name" in notice_recs.columns:
                    scrapeRecords =    ScrapeRecords(owners_name = owner_name,property_value_current_year=property_value["Current Year (2020-21)"],
                    property_value_next_year = property_value["Next Year (2021-22)"],tax_value = tax_value,
                    billing_address = str(rec["house_number"])+ " "+str(rec["street_name"]) ,link = tax_value_link,
                    borough = rec["borough"] ,block= rec["block"],
                    lot = rec["lot"],record_ref = scrapeRecordsInventoryRef)   
                    scrapeRecords.save()        
                elif "billing_address" in notice_recs.columns:
                    scrapeRecords =    ScrapeRecords(owners_name = owner_name,property_value_current_year=property_value["Current Year (2020-21)"],
                    property_value_next_year = property_value["Next Year (2021-22)"],tax_value = tax_value,
                    billing_address = rec["billing_address"] ,link = tax_value_link,
                    borough = rec["borough"] ,block= rec["block"],
                    lot = rec["lot"],record_ref = scrapeRecordsInventoryRef)   
                    scrapeRecords.save() 
            except:
                    print("++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
                    print(sys.exc_info())                
                    if "street_name" in notice_recs.columns:
                        try:
                            print("EXCEPT EXCEPT STREET NAME")
                            undoneNotices = UndoneNotices(borough = rec["borough"],block = rec["block"],lot = rec["lot"]

spider1/templates/home.html
{% extends 'home_layout.html' %}

{% block title %}
Home
				{% endblock %}

{% block content %}
<div class="row">
<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            Notice Records
        </div>
        <div class="panel-body">
            <span class="badge m-left-xs"><button id = "add_notice" class = "btn btn-lg btn-success">Add Notice</button></span>
            
        </div>
        {% if inv_recs_error %}
      <div class="alert alert-danger alert-dismissable">
        <button aria-hidden="true" data-dismiss="alert" class="close" type="button"> × </button>
        Error ! Try again please. </div>
    </div>
						{% endif %}
        <table class="table table-bordered table-condensed table-hover table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Rec Name</th>
                    <th>Time of Record</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {% for scrape_inventory_rec in scrape_inventory_recs %}
                <tr> 
                    <td><a href="{% url 'spider1:inv_rec_detail' scrape_inventory_rec.pk %}">{{scrape_inventory_rec.pk}}</a></td> 
                    <td>{{scrape_inventory_rec.rec_date}}</td>
                    <td>{{scrape_inventory_rec.time_rec}}</td> 
                    <td></td>


                </tr> 
                {% endfor %}
                <!-- <tr>
                    <td>
                        3242
                    </td>
                    <td>
                        John Doe
                    </td>
                    <td>
                        Oct 08,2013
                    </td>
                    <td>
                        <span class="label label-warning">Pending</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        3243
                    </td>
                    <td>
                        Jahn Doe
                    </td>
                    <td>
                        Oct 07,2013
                    </td>
                    <td>
                        <span class="label label-warning">Pending</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        3244
                    </td>
                    <td>
                        Bill Doe
                    </td>
                    <td>
                        29 Sep,2013
                    </td>
                    <td>
                        <span class="label label-success">Approved</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        3245
                    </td>
                    <td>
                        Kate Doe
                    </td>
                    <td>
                        19 July,2013
                    </td>
                    <td>
                        <span class="label label-success">Approved</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        3246
                    </td>
                    <td>
                        Jame Doe
                    </td>
                    <td>
                        18 July,2013
                    </td>
                    <td>
                        <span class="label label-danger">Banned</span>
                    </td>
                </tr> -->
            </tbody>
        </table>
    </div><!-- /panel -->
<form id ="random_form">
    {% csrf_token %}
  

</form>
</div><!-- /.col -->
</div>

    {% endblock %}

spider1/templates/home_layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    {% block title %}
                    {% endblock %}
        {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	
	<!-- Font Awesome-->
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

	<!-- Pace -->
	<link href="{% static 'css/pace.css' %}" rel="stylesheet">
	
	<!-- Datatable -->
	<link href="{% static 'css/jquery.dataTables_themeroller.css' %}" rel="stylesheet">
	
	<!-- Endless -->
	<link href="{% static 'css/endless.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/endless-skin.css' %}" rel="stylesheet">
	
  </head>

  <body class="pace-done">

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
<div id ="wrapper">









	<aside class="fixed skin-6">			
		<div class="sidebar-inner scrollable-sidebar">
			<div class="size-toggle">
				<a class="btn btn-sm" id="sizeToggle">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<a class="btn btn-sm pull-right logoutConfirm_open"  href="#logoutConfirm">
					<i class="fa fa-power-off"></i>
				</a>
			</div><!-- /size-toggle -->	
			<div class="user-block clearfix">
				<img src="img/user.jpg" alt="User Avatar">
				<div class="detail">
					<strong>John Doe</strong><span class="badge badge-danger bounceIn animation-delay4 m-left-xs">4</span>
					<ul class="list-inline">
						<li><a href="profile.html">Profile</a></li>
						<li><a href="inbox.html" class="no-margin">Inbox</a></li>
					</ul>
				</div>
			</div><!-- /user-block -->
			<div class="search-block">
				<div class="input-group">
					<input type="text" class="form-control input-sm" placeholder="search here...">
					<span class="input-group-btn">
						<button class="btn btn-default btn-sm" type="button"><i class="fa fa-search"></i></button>
					</span>
				</div><!-- /input-group -->
			</div><!-- /search-block -->
			<div class="main-menu">
				<ul>

					<li>
						<a href="{% url 'spider1:home' %}">
							<span class="menu-icon">
								<i class="fa fa-desktop fa-lg"></i> 
							</span>
							<span class="text">
								Home
							</span>
							<span class="menu-hover"></span>
						</a>
					</li>
					<!-- <li>
						<a href="{% url 'spider1:create_db_notice' %}">
							<span class="menu-icon">
								<i class="fa fa-desktop fa-lg"></i> 
							</span>
							<span class="text">
								Create New Notice
							</span>
							<span class="menu-hover"></span>
						</a>
					</li>
					<li>
						<a href="{% url 'spider1:create_db_notice' %}">
							<span class="menu-icon">
								<i class="fa fa-desktop fa-lg"></i> 
							</span>
							<span class="text">
								Home
							</span>
							<span class="menu-hover"></span>
						</a>
					</li> -->

				</ul>
				
				<div class="alert alert-info">
					Welcome to Endless Admin. Do not forget to check all my pages. 
				</div>
			</div><!-- /main-menu -->
		</div><!-- /sidebar-inner scrollable-sidebar -->
	</aside>





















<div id = "main-container">
<div class = "padding-md">
	{% block content %}
    {% endblock %}
</div>
</div>
</div>
    



	<!-- Jquery -->
	<script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
	
		<!-- Bootstrap -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
 
	<!-- Datatable -->
	<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>	
	

	
	<!-- Modernizr -->
	<script src="{% static 'js/modernizr.min.js' %}"></script>
	
	<!-- Pace -->
	<script src="{% static 'js/pace.min.js' %}"></script>
	
	<!-- Popup Overlay -->
	<script src= "{% static 'js/jquery.popupoverlay.min.js' %}"></script>
	
	 <!-- Slimscroll -->
	<script src="{% static 'js/jquery.slimscroll.min.js' %}"></script>
	
	<!-- Cookie -->
	<script src="{% static 'js/jquery.cookie.min.js' %}"></script>

	<!-- Endless -->
	<script src="{% static 'js/endless/endless.js' %}"></script>
	<script src="{% static 'js/endless/endless.js' %}"></script>
	<script src="{% static 'js/scraper_nyc.js' %}"></script>

	
	<script>
		$(function	()	{
			$('#dataTable').dataTable( {
				"bJQueryUI": true,
				"sPaginationType": "full_numbers"
			});
			
			$('#chk-all').click(function()	{
				if($(this).is(':checked'))	{
					$('#responsiveTable').find('.chk-row').each(function()	{
						$(this).prop('checked', true);
						$(this).parent().parent().parent().addClass('selected');
					});
				}
				else	{
					$('#responsiveTable').find('.chk-row').each(function()	{
						$(this).prop('checked' , false);
						$(this).parent().parent().parent().removeClass('selected');
					});
				}
			});
		});
	</script>
	
  </body>
</html>

spider1/templates/undone_rec_list.html
{% extends 'home_layout.html' %}

{% block title %}
Home
				{% endblock %}

{% block content %}
<div class="row">
<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            Notice Records
        </div>
        <div class="panel-body">
            <span class="badge m-left-xs"><button id = "add_notice" class = "btn btn-lg btn-success">Add Notice</button></span>
            
        </div>
        {% if undone_notices_errors %}
      <div class="alert alert-danger alert-dismissable">
        <button aria-hidden="true" data-dismiss="alert" class="close" type="button"> × </button>
        Error ! Try again please. </div>
    </div>
						{% endif %}
        <table class="table table-bordered table-condensed table-hover table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Rec Name</th>
                    <th>Time of Record</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {% for rec in undone_notices %}
                borough
block
lot
exception_type
billing_address
time_exception
exception_info
                <tr> 
                    <td><a href="{% url 'spider1:inv_rec_detail' scrape_inventory_rec.pk %}">{{rec.pk}}</a></td> 
                    <td>{{rec.borough}}</td>
                    <td>{{rec.block}}</td>
                    <td>{{rec.lot}}</td> 
                    <td>{{rec.exception_type}}</td> 
                    <td>{{rec.billing_address}}</td> 
                    <td>{{rec.time_exception}}</td> 
                    <td>{{rec.exception_info}}</td> 


                </tr> 
                {% endfor %}
                <!-- <tr>
                    <td>
                        3242
                    </td>
                    <td>
                        John Doe
                    </td>
                    <td>
                        Oct 08,2013
                    </td>
                    <td>
                        <span class="label label-warning">Pending</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        3243
                    </td>
                    <td>
                        Jahn Doe
                    </td>
                    <td>
                        Oct 07,2013
                    </td>
                    <td>
                        <span class="label label-warning">Pending</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        3244
                    </td>
                    <td>
                        Bill Doe
                    </td>
                    <td>
                        29 Sep,2013
                    </td>
                    <td>
                        <span class="label label-success">Approved</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        3245
                    </td>
                    <td>
                        Kate Doe
                    </td>
                    <td>
                        19 July,2013
                    </td>
                    <td>
                        <span class="label label-success">Approved</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        3246
                    </td>
                    <td>
                        Jame Doe
                    </td>
                    <td>
                        18 July,2013
                    </td>
                    <td>
                        <span class="label label-danger">Banned</span>
                    </td>
                </tr> -->
            </tbody>
        </table>
    </div><!-- /panel -->
<form id ="random_form">
    {% csrf_token %}

</form>
</div><!-- /.col -->
</div>

    {% endblock %}

spider1/templates/undone_recs.html
{% extends 'home_layout.html' %}

{% block title %}
Undone Records
				{% endblock %}
{% block content %}

    {% if undone_notices_errors %}
    <div class="alert alert-danger alert-dismissable">
      <button aria-hidden="true" data-dismiss="alert" class="close" type="button"> × </button>
      Error ! Try again please. </div>
  
                      {% endif %}
 <div id ="my_alert_box"></div>
 <a href = "{% url 'spider1:handle_undone_notices' undone_notices.id %}" id ="handle_undone_notices"class="btn btn-danger btn-md">Handle Undone</a>
 {{undone_notices.id}}
<div class="panel panel-default table-responsive">
    <div class="panel-heading">
        Data Table
        <span class="label label-info pull-right">790 Items</span>
    </div>
    <div class="padding-md clearfix">
        <table class="table table-striped" id="dataTable">
            <thead>
                <tr>
                    <!-- <th>No</th>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Sales</th>
                    <th>Date</th>
                    <th>Status</th> -->
                    <th>Borough</th>
                    <th>Block</th>
                    <th>Lot</th>
                    <th>Exception Type</th>
                    <th>Billing Address</th>
                    <th>Exception Time</th>
                    <th>Scrape Rec</th>
                    <th>Exception Info</th>
                </tr>
            </thead>
            <tbody>
                {% for rec in undone_notices.undone_rec %}
                <tr>
                    <td>{{rec.borough}}</td>
                    <td>{{rec.block}}</td>
                    <td>{{rec.lot}}</td>
                    <td>{{rec.exception_type}}</td>
                    <td>{{rec.billing_address}}</td>
                    <td>{{rec.time_exception}}</td>
                    <td>{{rec.scrape_rec}}</td>
                    <td>{{rec.exception_info}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div><!-- /.padding-md -->
</div><!-- /panel -->

{% endblock %}